### ISSUE TITLE
Jekyll compatibility ?

### ISSUE THREAD

**Issue by taophp** [lise-henry/crowbook#2]
As I use markdown first to publish my texts using Jekyll, my markdown files are builds the Jekyll way. So they have a YALM header. At least, I expect Crowbook to ignore them, so I would not have to manage two versions of each text. But this is not the case, and the result is ugly.

Suggestion:  it should be even better if the YAML header could be use by crowbook instead of an external configuration file. Maybe a YAML key named `crowbook` should be use to avoid conflict of key naming between Jekyll and Crowbook. So the file header should look like: 
```
---
layout: post
title:  Disparition
date: 2016-01-18 00:30:05
categories: blog
type: nouvelle
crowbook:
  title: Disparition
  author: Stéphane Mourey
  lang: fr
---
And now, for your pleasure, a brand new history....
```
---

Suggestion 2: there should be some redundant keys, like the `title` one in my sample. So, may crowbook read the whole YAML to get them, instead of repeating them in the file. I don't know, just thinking.
