### ISSUE TITLE
Bookmarks vs. inline code in md

### ISSUE THREAD

**Issue by jrappen** [lise-henry/crowbook#69]
When adding:

```latex
\usepackage[
  usenames,
  dvipsnames,
  svgnames
]{xcolor}
```

to the `template.tex` and changing the appearance of inline code in md to:

```diff
- \newcommand\mdcode[1]{\texttt{#1}}
+ \newcommand\mdcode[1]{\color{Red!33!Black} \texttt{#1}}
```

Bookmarks are messed up as follows:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/8577450/71299566-3b926700-238e-11ea-9c24-5c26a237917f.png">

---

```yaml
XeTeX    : 3.14159265-2.6-0.999991 (TeX Live 2019)
crowbook : v0.15.0
OS       : macOS Catalina 10.15.2 (19C57)
hardware : MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
```
