### ISSUE TITLE
Page numbers offset in TOC by -10

### ISSUE THREAD

**Issue by jrappen** [lise-henry/crowbook#70]
Page numbers are offset in TOC by `-10`.

<details>
<summary>Image 1 (click to reveal)</summary>
<img width="513" alt="image" src="https://user-images.githubusercontent.com/8577450/71547576-17dcab80-29a2-11ea-832a-62d7a57ffc98.png">
</details>

<details>
<summary>Image 2 (click to reveal)</summary>
<img width="685" alt="image" src="https://user-images.githubusercontent.com/8577450/71547587-3b9ff180-29a2-11ea-9f5f-d921ae078000.png">
</details>

Side note: Although the images here show the use of a custom LaTeX template, I can reproduce this with the LaTeX template shipping with `crowbook`.

```yaml
XeTeX    : 3.14159265-2.6-0.999991 (TeX Live 2019)
crowbook : v0.15.0
OS       : macOS Catalina 10.15.2 (19C57)
hardware : MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
```
